version: '3'

services:
    pade:
        container_name: pade
        build: .
        command: pade start-runtime --config_file config.json
        ports:
            - "8080:8000"
            - "8081:20000"
            - "8082:8001"
            - "8083:5000"
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - .:/opt/app
        environment:
        - DISPLAY=$DISPLAY

